services:
  # FastAPI Application - Connects to Local Databases
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: chatbot-api
    ports:
      - "8000:8000"
    environment:
      - .env
    volumes:
      - api_data:/app/var
    extra_hosts:
      # Allow container to access host machine's databases
      - "host.docker.internal:host-gateway"
    networks:
      - chatbot-network
    restart: unless-stopped

volumes:
  api_data:
    driver: local

networks:
  chatbot-network:
    driver: bridge
